# Generated by Django 3.1.7 on 2021-03-25 22:17

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import py_dev_user.utilities
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.categorymodel', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='SellerModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Seller',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='Tag')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
            ],
            options={
                'verbose_name': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(db_index=True, max_length=100, verbose_name='Object name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=py_dev_user.utilities.get_timestamp_path, verbose_name='Image')),
                ('type', models.CharField(choices=[('a', 'Apartment'), ('h', 'House'), ('o', 'Hotel'), ('s', 'Hostel')], db_index=True, default='a', help_text='Apartment, House, Hotel, Hostel', max_length=10, verbose_name='Type')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('item_create', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('item_update', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.categorymodel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sellermodel')),
                ('tag', models.ManyToManyField(blank=True, to='main.TagModel')),
            ],
            options={
                'verbose_name': 'Item',
            },
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=py_dev_user.utilities.get_timestamp_path, verbose_name='Image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.itemmodel', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Additional imge',
                'verbose_name_plural': 'Additional images',
            },
        ),
    ]
