# Generated by Django 3.1.7 on 2021-03-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_itemmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
