# Generated by Django 3.1.7 on 2021-03-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_itemmodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25, verbose_name='Полное имя')),
                ('short_name', models.CharField(max_length=5, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'Currency',
            },
        ),
    ]
