# Generated by Django 3.1.7 on 2021-03-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210326_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='In stock'),
        ),
    ]
