# Generated by Django 3.1.7 on 2021-04-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
