# Generated by Django 3.1.7 on 2021-04-22 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_send', models.BooleanField(default=False)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.itemmodel')),
            ],
            options={
                'verbose_name': 'Item report',
                'ordering': ['-is_send'],
            },
        ),
    ]
